import test from 'node:test';import assert from 'node:assert/strict';
import {Tracker,flightDuration} from '../public/tracker.mjs';
import {AIRFIELDS} from '../public/airfields.mjs';
import {parseAdsb} from '../public/traffic.mjs';
import {periodDays,completedAirTime,launchCount,localRecord} from '../public/logbook.mjs';
const base=Date.parse('2026-10-05T10:00:00Z'),cfg=AIRFIELDS.predannack;
const sample=(seconds,extra={})=>({deviceId:'43BC89',cn:'PDANNACK',lat:cfg.lat,lon:cfg.lon,reportAt:base+seconds*1000,altitudeM:90,speedKmh:0,source:'ADSB',altitudeReference:'barometric',...extra});
const update=(t,sec,extra)=>t.update([sample(sec,extra)],base+sec*1000);
test('pressure altitude is preferred and geometric altitude stays labelled separately',()=>{const [a]=parseAdsb({now:base/1000,ac:[{hex:'43bc89',lat:50,lon:-5,seen_pos:0,alt_baro:300,alt_geom:600}]});assert.equal(a.altitudeM,91.44);assert.equal(a.geometricAltitudeM,182.88);assert.equal(a.altitudeReference,'barometric')});
test('PDANNACK first seen flying is partial activity, never a confirmed launch or completed air time',()=>{const t=new Tracker({},cfg);update(t,0,{altitudeM:180,speedKmh:90});update(t,60,{altitudeM:200,speedKmh:90});assert.equal(t.flights.length,1);assert.equal(t.flights[0].partial,true);assert.equal(t.flights[0].aircraftType,'G103');assert.equal(launchCount(t.flights,cfg.origin),0);update(t,120);update(t,180);assert.ok(t.flights[0].landingAt);assert.equal(completedAirTime(t.flights),0)});
test('high aircraft and non-PDANNACK aircraft do not create Predannack club flights',()=>{for(const extra of [{altitudeM:2000,speedKmh:90},{cn:'OTHER',altitudeM:180,speedKmh:90}]){const t=new Tracker({},cfg);update(t,0);update(t,60,extra);update(t,120,extra);assert.equal(t.flights.length,0)}});
test('ground flag calibrates pressure offset and event times are bracketed by observations',()=>{const t=new Tracker({},cfg);update(t,0,{onGround:true,altitudeM:180});update(t,60,{altitudeM:250,speedKmh:90});update(t,120,{altitudeM:300,speedKmh:90});update(t,180,{onGround:true,altitudeM:180});update(t,240,{onGround:true,altitudeM:180});const f=t.flights[0];assert.equal(f.heightBaselineM,180);assert.equal(f.maxRelativeHeightM,120);assert.deepEqual(f.takeoffWindow,[base,base+60000]);assert.deepEqual(f.landingWindow,[base+120000,base+180000]);assert.equal(launchCount(t.flights,cfg.origin),1);assert.equal(completedAirTime(t.flights),120000)});
test('ellipsoid altitude may capture partial activity without claiming a launch',()=>{const t=new Tracker({},cfg);update(t,0,{altitudeReference:'ellipsoid',altitudeM:180,speedKmh:90});update(t,60,{altitudeReference:'ellipsoid',altitudeM:200,speedKmh:90});assert.equal(t.flights.length,1);assert.equal(t.flights[0].partial,true);assert.equal(launchCount(t.flights,cfg.origin),0)});
test('an established local flight may climb high without being removed',()=>{const t=new Tracker({},cfg);update(t,0);update(t,60,{altitudeM:180,speedKmh:90});update(t,120,{altitudeM:200,speedKmh:90});update(t,180,{altitudeM:1500,speedKmh:100});assert.equal(t.flights.length,1);assert.equal(t.flights[0].maxRelativeHeightM,1410);assert.equal(localRecord(t.flights[0],cfg.origin),true)});
test('airborne duration stops at actual latest report, not reception time',()=>{assert.equal(flightDuration({takeoffAt:base,lastReportAt:base+60000,status:'AIRBORNE'},base+90000),60000)});
test('calendar periods handle Monday start, leap years and month boundaries',()=>{assert.equal(periodDays('2026-10-06','week').length,2);assert.equal(periodDays('2026-10-06','month').length,6);assert.equal(periodDays('2024-12-31','year').length,366);assert.equal(periodDays('2026-01-01','year').length,1)});

test('low barometric PDANNACK activity is retained as partial, not invented launches',()=>{const t=new Tracker({},cfg);update(t,0,{altitudeM:91.44,speedKmh:94});update(t,60,{altitudeM:92,speedKmh:94});assert.equal(t.flights.length,1);assert.equal(t.flights[0].partial,true);assert.equal(launchCount(t.flights,cfg.origin),0)});
test('second launch confirmation may be above initial launch ceiling',()=>{const t=new Tracker({},cfg);update(t,0);update(t,60,{altitudeM:180,speedKmh:90});update(t,120,{altitudeM:600,speedKmh:90});assert.equal(t.flights.length,1);assert.equal(t.flights[0].departureConfirmed,true)});

test('low signal loss marks probable landing and return reopens same flight',()=>{const t=new Tracker({},cfg);update(t,0,{altitudeM:140,speedKmh:90});t.tick(base+180000);assert.equal(t.flights[0].status,'PROBABLE_LANDING');assert.equal(t.flights[0].landingAt,null);update(t,240,{altitudeM:200,speedKmh:90});assert.equal(t.flights.length,1);assert.equal(t.flights[0].probableLandingAt,undefined)});
test('first-seen airborne glider within5km is kept with unknown launch',()=>{const a=AIRFIELDS.brentor,t=new Tracker({},a);t.update([{deviceId:'D',vehicleType:'1',lat:a.lat+.02,lon:a.lon,altitudeM:900,speedKmh:90,reportAt:base}],base);assert.equal(t.flights.length,1);assert.equal(t.flights[0].partial,true);assert.equal(launchCount(t.flights,a.origin),0)});

test('two low slow local reports mark probable landing without claiming touchdown',()=>{const t=new Tracker({},cfg);update(t,0,{altitudeM:200,speedKmh:90});update(t,60,{altitudeM:120,speedKmh:55});update(t,120,{altitudeM:120,speedKmh:55});assert.equal(t.flights[0].status,'PROBABLE_LANDING');assert.equal(t.flights[0].landingAt,null)});
