import test from 'node:test';import assert from 'node:assert/strict';
import {Tracker,flightDuration,dayKey,validateCorrection,inside,DEFAULTS} from '../public/tracker.mjs';
import {parseOgn} from '../lib/ogn.mjs';
const base=Date.parse('2026-10-04T10:00:00Z');
const a=(sec,extra={})=>({deviceId:'D01496',registration:'G-DDSL',lat:50.5922,lon:-4.1517,altitudeM:279,speedKmh:0,reportAt:base+sec*1000,...extra});
const flying=sec=>a(sec,{altitudeM:400,speedKmh:90});
function launch(){const t=new Tracker();t.update([a(0)],base);t.update([flying(15)],base+15000);t.update([flying(30)],base+30000);return t}
test('parser reads OGN altitude, age, heading and speed correctly',()=>{const rows=parseOgn('<markers><m a="50.592121,-4.143880,DSL,G-DDSL,260,10:00:00,21,155,90,-0.1,1,BRENTOR,D01496,d0bb7e8d"/></markers>',base+21000);assert.equal(rows[0].altitudeM,260);assert.equal(rows[0].speedKmh,90);assert.equal(rows[0].trackDeg,155);assert.equal(rows[0].reportAt,base)});
test('ground then two distinct flying reports produces one Brentor flight',()=>{const t=launch();assert.equal(t.flights.length,1);assert.equal(t.flights[0].origin,'BRENTOR');assert.equal(t.flights[0].takeoffAt,base+15000)});
test('repeat reports cannot trigger launch even with reception clock jitter',()=>{const t=new Tracker();t.update([a(0)],base);t.update([flying(15)],base+15000);for(let i=0;i<8;i++)t.update([flying(15+i*.2)],base+30000+i*1000);assert.equal(t.flights.length,0)});
test('old or future positions do not create flights',()=>{const t=new Tracker();t.update([flying(0)],base+100000);t.update([flying(15)],base+120000);t.update([flying(500)],base+120000);assert.equal(t.flights.length,0)});
test('aircraft first seen airborne does not create a local flight record',()=>{const t=new Tracker();t.update([flying(0)],base);t.update([flying(15)],base+15000);assert.equal(t.flights.length,0)});
test('refresh preserves active tracking and prevents duplicate flights',()=>{const t=new Tracker(JSON.parse(JSON.stringify(launch().snapshot())));t.update([flying(45)],base+45000);t.update([flying(60)],base+60000);assert.equal(t.flights.length,1)});
test('lost signal freezes observed duration without claiming landing',()=>{const t=launch();t.update([],base+160000);assert.equal(t.flights[0].status,'LOST');assert.equal(t.flights[0].landingAt,null);assert.equal(flightDuration(t.flights[0],base+400000),15000);t.update([flying(180)],base+180000);assert.equal(t.flights.length,1);assert.equal(t.flights[0].status,'AIRBORNE');assert.equal(t.flights[0].closedUnresolved,undefined)});
test('flight under two minutes can land after two fresh ground reports',()=>{const t=launch();t.update([a(45)],base+45000);t.update([a(60)],base+60000);assert.equal(t.flights[0].landingAt,base+45000);assert.equal(t.flights[0].status,'LANDED')});
test('ground report outside airfield does not claim Brentor landing',()=>{const t=launch();t.update([a(45,{lat:50.63})],base+45000);t.update([a(60,{lat:50.63})],base+60000);assert.equal(t.flights[0].landingAt,null)});
test('missing altitude or speed does not confirm landing',()=>{const t=launch();t.update([a(45,{altitudeM:null})],base+45000);t.update([a(60,{speedKmh:null})],base+60000);assert.equal(t.flights[0].landingAt,null)});
test('next launch after landing is a separate flight',()=>{const t=launch();t.update([a(45)],base+45000);t.update([a(60)],base+60000);t.update([flying(75)],base+75000);t.update([flying(90)],base+90000);assert.equal(t.flights.length,2);assert.equal(t.flights[1].origin,'BRENTOR')});
test('London day boundary is used in summer and winter',()=>{assert.equal(dayKey(Date.parse('2026-10-04T23:10:00Z')),'2026-10-05');assert.equal(dayKey(Date.parse('2026-12-04T23:10:00Z')),'2026-12-04')});
test('custom boundary supports polygon inclusion',()=>{const cfg={...DEFAULTS,polygon:[[50.59,-4.16],[50.60,-4.16],[50.60,-4.14],[50.59,-4.14]]};assert.equal(inside(a(0),cfg),true);assert.equal(inside(a(0,{lat:50.7}),cfg),false)});
test('manual record correction rejects reversed times',()=>{assert.throws(()=>validateCorrection({registration:'G-DDSL',origin:'BRENTOR',takeoffAt:base,landingAt:base-1}));assert.equal(validateCorrection({registration:'G-DDSL',origin:'BRENTOR',takeoffAt:base,landingAt:null}).manual,true)});
test('manual landing permits a subsequent launch without losing original detection',()=>{const t=launch(),f=t.flights[0];t.reconcile({[f.id]:{landingAt:base+45000}});assert.equal(f.landingAt,null);assert.equal(f.closedByCorrection,true);t.update([a(60)],base+60000);t.update([flying(75)],base+75000);t.update([flying(90)],base+90000);assert.equal(t.flights.length,2)});
test('return after a six-hour gap does not extend an unresolved flight into the next session',()=>{const t=launch();t.update([a(22000)],base+22000000);assert.equal(t.flights[0].closedUnresolved,true);assert.equal(t.flights[0].lastReportAt,base+30000);t.update([flying(22015)],base+22015000);t.update([flying(22030)],base+22030000);assert.equal(t.flights.length,2)});

